name: Backend CI/CD

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yml"
      - "render.yaml"
    branches: [ "main" ]
  pull_request:
    paths: [ "backend/**", "render.yaml" ]

jobs:
  ci:
    name: Test backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('backend/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # optional: linters
          pip install black flake8 pytest

      - name: Lint
        run: |
          black --check .
          flake8

      - name: Run tests
        env:
          DJANGO_SETTINGS_MODULE: config.settings
          SECRET_KEY: test-secret
          # Use SQLite for CI by default:
          DATABASE_URL: sqlite:///test.sqlite3
        run: |
          pytest -q

  deploy:
    name: Deploy backend (Render)
    needs: ci
    if: github.ref == 'refs/heads/main' && needs.ci.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render deploy
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ secrets.RENDER_BACKEND_SERVICE_ID }}
        run: |
          curl -fsSL -X POST "https://api.render.com/v1/services/${SERVICE_ID}/deploys" \
            -H "Authorization: Bearer ${RENDER_API_KEY}" \
            -H "Content-Type: application/json" \
            -d '{"clearCache": false}'
